import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    backgroundColor: 'white',
  },
  text1: {
    width: 276,
    fontWeight: '600',
    fontSize: 20,
    marginLeft: 15,
  },
  text2: {
    width: 276,
    fontWeight: '400',
    fontSize: 14,
    marginLeft: 15,
    marginTop: 5,
  },
  // text3: {
  //   height: 48,
  //   fontWeight: '500',
  //   fontSize: 15,
  //   paddingLeft: 10,
  //   paddingTop: 15,
  //   color: '#1B2E72',
  // },
  text4: {
    fontWeight: '400',
    fontSize: 15,
    marginTop: 10,
    textAlign: 'center',
    color: 'red',
    shadowOpacity: 0.2,
  },
  edit: {
    position: 'absolute',
    padding: 4,
    zIndex: 1,
    alignSelf: 'flex-end',
  },
  profilePhoto: {
    width: 150,
    height: 150,
    borderRadius: 75,
  },
  cameraIcon: {
    position: 'absolute',
    bottom: 5,
    right: 5,
    backgroundColor: 'white',
    padding: 5,
    borderRadius: 15,
  },
  delete: {
    color: 'red',
    textAlign: 'center',
    fontSize: 20,
    fontWeight: '400',
    shadowOpacity: 0.1,
    marginTop: 15,
  },
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.3)',
  },
  modalView: {
    width: 385,
    height: 380,
    backgroundColor: 'white',
    borderRadius: 10,
    padding: 20,
    alignItems: 'center',
    elevation: 5,
  },
  modalView2: {
    width: 385,
    height: 260,
    backgroundColor: 'white',
    borderRadius: 10,
    padding: 20,
    alignItems: 'center',
    elevation: 5,
  },
  modalHeading: {
    fontSize: 20,
    fontWeight: '700',
    marginBottom: 10,
    marginTop: 10,
    textAlign: 'center',
    color: '#1B2E72',
  },
  eyeIcon: {
    position: 'absolute',
    paddingHorizontal: 14,
    paddingTop: 25,
    zIndex: 1,
  },
  rowIcon: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },

  card: {
    width: 350,
    height: '63.8%',
    alignItems: 'center',
    backgroundColor: 'white',
    borderRadius: 15,
    shadowColor: '#000',
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 3,
    justifyContent: 'center',
    borderWidth: 0.4,
    borderColor: '#1B2E72',
  },
  cardImg: {
    backgroundColor: '#F1C40F',
    height: 150,
    width: 150,
    borderRadius: 75,
  },
  textTitle: {
    fontWeight: '900',
    fontSize: 16,
    lineHeight: 24,
    marginTop: 15,
    color: '#1B2E72',
  },
  textBody: {
    fontSize: 16,
    marginBottom: 15,
    fontWeight: '400',
  },
  cardFooter: {
    width: '90%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: '#ddd',
    marginTop: 20,
    marginBottom: 20,
  },
  button: {
    position: 'relative',
    alignSelf: 'flex-end',
    // bottom: 24,
    alignItems: 'center',
    justifyContent: 'center',
    width: 30,
    height: 32,
    backgroundColor: '#F1C40F',
    borderTopRightRadius: 14,
    borderTopLeftRadius: 0,
    borderBottomRightRadius: 0,
    borderBottomLeftRadius: 10,
    // borderLeftWidth:4,
    // borderBottomWidth:4,
    // borderColor: 'gray'
    // shadowColor: '#D4AD0B',
    // shadowOffset: {width: -3, height: 3},
    // shadowOpacity: 1,
    // shadowRadius: 3,
  },
});

export default styles;
